-- Generated by Oracle SQL Developer Data Modeler 20.4.0.374.0801
--   at:        2021-09-16 16:24:40 IST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

--student id: 30769140
--student name: Sadeeptha Bandara

-- Capture run of script in file called property_rental_schema_output.txt
set echo on
SPOOL property_rental_schema_output.txt


DROP TABLE damage CASCADE CONSTRAINTS;

DROP TABLE maintenance CASCADE CONSTRAINTS;

DROP TABLE owner CASCADE CONSTRAINTS;

DROP TABLE payment CASCADE CONSTRAINTS;

DROP TABLE payment_method CASCADE CONSTRAINTS;

DROP TABLE property CASCADE CONSTRAINTS;

DROP TABLE rent CASCADE CONSTRAINTS;

DROP TABLE tenant CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE damage (
    damage_no          NUMBER(7) NOT NULL,
    dam_datetime       DATE NOT NULL,
    rent_agreement_no  NUMBER(7) NOT NULL,
    dam_type           VARCHAR2(50) NOT NULL,
    dam_cost           NUMBER(7, 2) NOT NULL,
    pay_no             NUMBER(7)
);

COMMENT ON COLUMN damage.damage_no IS
    'Damage number';

COMMENT ON COLUMN damage.dam_datetime IS
    'Damage date';

COMMENT ON COLUMN damage.rent_agreement_no IS
    'Rental agreement number';

COMMENT ON COLUMN damage.dam_type IS
    'Damage type';

COMMENT ON COLUMN damage.dam_cost IS
    'Damage cost';

COMMENT ON COLUMN damage.pay_no IS
    'Payment number';

CREATE UNIQUE INDEX damage__idx ON
    damage (
        pay_no
    ASC );

ALTER TABLE damage ADD CONSTRAINT damage_pk PRIMARY KEY ( damage_no );

ALTER TABLE damage ADD CONSTRAINT damage_nk UNIQUE ( rent_agreement_no,
                                                     dam_datetime );

CREATE TABLE maintenance (
    prop_no         NUMBER(7) NOT NULL,
    maint_datetime  DATE NOT NULL,
    maint_desc      VARCHAR2(50) NOT NULL,
    maint_cost      NUMBER(7, 2) NOT NULL
);

COMMENT ON COLUMN maintenance.prop_no IS
    'property number';

COMMENT ON COLUMN maintenance.maint_datetime IS
    'Maintenance date time';

COMMENT ON COLUMN maintenance.maint_desc IS
    'Maintenance Description';

COMMENT ON COLUMN maintenance.maint_cost IS
    'Maintenance cost';

ALTER TABLE maintenance ADD CONSTRAINT maintenance_pk PRIMARY KEY ( maint_datetime,
                                                                    prop_no );

CREATE TABLE owner (
    owner_no       NUMBER(7) NOT NULL,
    owner_givname  VARCHAR2(50),
    owner_famname  VARCHAR2(50),
    owner_address  VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN owner.owner_no IS
    'owner id';

COMMENT ON COLUMN owner.owner_givname IS
    'owner''s given  name
';

COMMENT ON COLUMN owner.owner_famname IS
    'owner''s family  name
';

COMMENT ON COLUMN owner.owner_address IS
    'Onwer address';

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_no );

CREATE TABLE payment (
    pay_no             NUMBER(7) NOT NULL,
    pay_date           DATE NOT NULL,
    pay_type           CHAR(1) NOT NULL,
    pay_amount         NUMBER(7, 2) NOT NULL,
    pay_method_no      NUMBER(7) NOT NULL,
    rent_agreement_no  NUMBER(7) NOT NULL
);

ALTER TABLE payment
    ADD CONSTRAINT chk_payment_type CHECK ( pay_type IN ( 'B', 'D', 'R' ) );

COMMENT ON COLUMN payment.pay_no IS
    'Payment number';

COMMENT ON COLUMN payment.pay_date IS
    'Payment date';

COMMENT ON COLUMN payment.pay_type IS
    'Payment type: Rental, Damage, Bond';

COMMENT ON COLUMN payment.pay_amount IS
    'Payment amount';

COMMENT ON COLUMN payment.pay_method_no IS
    'Payment type number';

COMMENT ON COLUMN payment.rent_agreement_no IS
    'Rental agreement number';

ALTER TABLE payment ADD CONSTRAINT payment_pk PRIMARY KEY ( pay_no );

CREATE TABLE payment_method (
    pay_method_no    NUMBER(7) NOT NULL,
    pay_method_name  VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN payment_method.pay_method_no IS
    'Payment type number';

COMMENT ON COLUMN payment_method.pay_method_name IS
    'Payment type name';

ALTER TABLE payment_method ADD CONSTRAINT payment_type_pk PRIMARY KEY ( pay_method_no );

CREATE TABLE property (
    prop_no       NUMBER(7) NOT NULL,
    prop_address  VARCHAR2(50) NOT NULL,
    prop_value    NUMBER(7, 2) NOT NULL,
    owner_no      NUMBER(7) NOT NULL
);

COMMENT ON COLUMN property.prop_no IS
    'property number';

COMMENT ON COLUMN property.prop_address IS
    'property address			';

COMMENT ON COLUMN property.prop_value IS
    'Property valuation	';

COMMENT ON COLUMN property.owner_no IS
    'owner id';

ALTER TABLE property ADD CONSTRAINT property_pk PRIMARY KEY ( prop_no );

CREATE TABLE rent (
    rent_agreement_no      NUMBER(7) NOT NULL,
    prop_no                NUMBER(7) NOT NULL,
    rent_lease_start_date  DATE NOT NULL,
    rent_bond              NUMBER(7, 2) NOT NULL,
    rent_lease_period      DATE NOT NULL,
    tenant_no              NUMBER(7) NOT NULL,
    rent_weekly_rate       NUMBER(7, 2) NOT NULL
);

COMMENT ON COLUMN rent.rent_agreement_no IS
    'Rental agreement number';

COMMENT ON COLUMN rent.prop_no IS
    'property number';

COMMENT ON COLUMN rent.rent_lease_start_date IS
    'Rent lease start date';

COMMENT ON COLUMN rent.rent_bond IS
    'Rent bond';

COMMENT ON COLUMN rent.rent_lease_period IS
    'Rent lease period';

COMMENT ON COLUMN rent.tenant_no IS
    'Tenant number';

COMMENT ON COLUMN rent.rent_weekly_rate IS
    'Rent weekly rate';

ALTER TABLE rent ADD CONSTRAINT rent_pk PRIMARY KEY ( rent_agreement_no );

ALTER TABLE rent ADD CONSTRAINT rental_nk UNIQUE ( prop_no,
                                                   rent_lease_start_date );

CREATE TABLE tenant (
    tenant_no       NUMBER(7) NOT NULL,
    tenant_givname  VARCHAR2(50),
    tenant_famname  VARCHAR2(50),
    tenant_address  VARCHAR2(50) NOT NULL,
    tenant_phone    CHAR(10) NOT NULL
);

COMMENT ON COLUMN tenant.tenant_no IS
    'Tenant number';

COMMENT ON COLUMN tenant.tenant_givname IS
    'Given name of tenant		';

COMMENT ON COLUMN tenant.tenant_famname IS
    'Family name of tenant';

COMMENT ON COLUMN tenant.tenant_address IS
    ' tenant''s address
';

COMMENT ON COLUMN tenant.tenant_phone IS
    'Tenant''s phone	';

ALTER TABLE tenant ADD CONSTRAINT tenant_pk PRIMARY KEY ( tenant_no );

ALTER TABLE damage
    ADD CONSTRAINT damage_payment FOREIGN KEY ( pay_no )
        REFERENCES payment ( pay_no );

ALTER TABLE property
    ADD CONSTRAINT owner_property FOREIGN KEY ( owner_no )
        REFERENCES owner ( owner_no );

ALTER TABLE maintenance
    ADD CONSTRAINT property_maint FOREIGN KEY ( prop_no )
        REFERENCES property ( prop_no );

ALTER TABLE rent
    ADD CONSTRAINT property_rent FOREIGN KEY ( prop_no )
        REFERENCES property ( prop_no );

ALTER TABLE payment
    ADD CONSTRAINT relation_11 FOREIGN KEY ( pay_method_no )
        REFERENCES payment_method ( pay_method_no );

ALTER TABLE damage
    ADD CONSTRAINT rent_damage FOREIGN KEY ( rent_agreement_no )
        REFERENCES rent ( rent_agreement_no );

ALTER TABLE payment
    ADD CONSTRAINT rent_payment FOREIGN KEY ( rent_agreement_no )
        REFERENCES rent ( rent_agreement_no );

ALTER TABLE rent
    ADD CONSTRAINT tenant_rent FOREIGN KEY ( tenant_no )
        REFERENCES tenant ( tenant_no );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             1
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


SPOOL off
set echo off
